# Generated by Django 4.0.6 on 2022-08-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(null=True, verbose_name='Numero de DNI'),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre_completo',
            field=models.CharField(default='Nombre Completo', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.IntegerField(choices=[[0, 'Hombre'], [1, 'Mujer'], [2, 'Otro'], [3, 'Prefiero no decirlo']], default='3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Correo Electronico'),
        ),
    ]
