# Generated by Django 4.0.6 on 2022-08-23 18:06

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_apellido_alter_user_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(default='27234834', max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(8)], verbose_name='N° DNI'),
        ),
    ]
