# Generated by Django 4.0.6 on 2022-08-24 03:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domicilio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provinicia',
            field=models.IntegerField(choices=[[0, 'Buenos Aires'], [1, 'CABA'], [2, 'Catamarca'], [3, 'Chaco'], [4, 'Chubut'], [5, 'Córdoba'], [6, 'Corrientes'], [7, 'Entre Ríos'], [8, 'Formosa'], [9, 'Jujuy'], [10, 'La Pampa'], [11, 'La Rioja'], [12, 'Mendoza'], [13, 'Misiones'], [14, 'Neuquén'], [15, 'Río Negro'], [16, 'Salta'], [17, 'San Juan'], [18, 'San Luis'], [19, 'Santa Cruz'], [20, 'Santa Fe'], [21, 'Santiago del Estero'], [22, 'Tierra del Fuego'], [23, 'Tucumán']], default='3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(8)], verbose_name='N° DNI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(8)], verbose_name='N° Telefono'),
        ),
    ]
