# Generated by Django 4.0.6 on 2022-08-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_provinicia_user_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre_completo',
        ),
    ]
