# Generated by Django 4.0.6 on 2022-08-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SOCIO', 'Socio'), ('VISITANTE', 'Visitante')], default='VISITANTE', max_length=12, verbose_name='Role'),
        ),
    ]
